# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('id_wbs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WbsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_current_booking_session', models.DateTimeField(default=None, null=True)),
                ('projects', models.ManyToManyField(related_name='wbs_users', to='id_wbs.DbIdentifier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
