# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_wbs', '__first__'),
        ('wbs_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workpackage_id', models.IntegerField()),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_wbs.DbIdentifier')),
            ],
        ),
        migrations.RemoveField(
            model_name='wbsuser',
            name='start_current_booking_session',
        ),
        migrations.AddField(
            model_name='bookingsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking_session', to='wbs_user.WbsUser'),
        ),
    ]
