# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wbs_user', '0002_auto_20160621_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 15, 8, 38, 159040, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
